import type { GamePresenter } from './presentation/presenter';

export const createTestPresenter = (overrides: Partial<GamePresenter> = {}): GamePresenter => ({
  setMode: () => {},
  publishStats: () => {},
  publishInventory: () => {},
  publishMap: () => {},
  publishLogs: () => {},
  publishDiscovery: () => {},
  publishEvent: () => {},
  updateStats: () => {},
  updateDropdowns: () => {},
  resetLog: () => {},
  renderLogs: () => {},
  syncDiscovery: () => {},
  render: () => {},
  fxPlayerRun: () => {},
  fxStrike: () => {},
  fxHit: () => {},
  fxFreeze: () => {},
  fxDeath: () => {},
  fxPlayerHit: () => {},
  fxDive: () => {},
  fxWhiff: () => {},
  fxFloat: () => {},
  fxMonsterDodge: () => {},
  mapRumble: () => {},
  beginFloorTransition: () => {},
  setAiming: () => {},
  focusCombatMonster: () => {},
  clearCombatFocusMonster: () => {},
  ...overrides,
});
